
package Ventanas;

import static conexion.conexion.getConection;
import static conexion.conexion.ps;
import static conexion.conexion.rs;
import java.awt.Image;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class registro extends javax.swing.JFrame {

    /**
     * Creates new form registro
     */
    public registro() {
        initComponents();
        ImageIcon imagen= new ImageIcon(getClass().getResource("/imagenes/Fondo.jpg"));
        Icon fondo=new ImageIcon(imagen.getImage().getScaledInstance(Fondo.getWidth(), Fondo.getHeight(), Image.SCALE_DEFAULT));
        Fondo.setIcon(fondo);
        TxtPass2.setText("");
        this.setLocationRelativeTo(null);
        ButtonGroup GrupoRad1 = new ButtonGroup();
        GrupoRad1.add(Rad1);
        GrupoRad1.add(Rad2);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoRad1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtUser = new javax.swing.JTextField();
        TxtPass1 = new javax.swing.JPasswordField();
        TxtPass2 = new javax.swing.JPasswordField();
        BtnAtras = new javax.swing.JButton();
        BtonConf = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Rad1 = new javax.swing.JRadioButton();
        Rad2 = new javax.swing.JRadioButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de usuario");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 84, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 128, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Confirmar contraseña");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 171, -1, -1));

        TxtUser.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TxtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUserActionPerformed(evt);
            }
        });
        getContentPane().add(TxtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 80, 163, -1));

        TxtPass1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TxtPass1.setText("jPasswordField1");
        TxtPass1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtPass1MouseClicked(evt);
            }
        });
        getContentPane().add(TxtPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 125, 163, -1));

        TxtPass2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TxtPass2.setText("jPasswordField2");
        TxtPass2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtPass2MouseClicked(evt);
            }
        });
        getContentPane().add(TxtPass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 168, 163, -1));

        BtnAtras.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BtnAtras.setText("Atras");
        BtnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 261, -1, -1));

        BtonConf.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BtonConf.setText("Confirmar");
        BtonConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtonConfActionPerformed(evt);
            }
        });
        getContentPane().add(BtonConf, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 261, -1, -1));

        jPanel1.setOpaque(false);

        Rad1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Rad1.setText("Admin");
        Rad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rad1ActionPerformed(evt);
            }
        });

        Rad2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Rad2.setText("Usuario");
        Rad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rad2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(Rad1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(Rad2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rad2)
                    .addComponent(Rad1))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 220, 50));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUserActionPerformed

    private void BtnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new login().setVisible(true);
    }//GEN-LAST:event_BtnAtrasActionPerformed

    private void BtonConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtonConfActionPerformed
        // TODO add your handling code here:
        String a= String.valueOf(TxtPass1.getPassword());
        String b= String.valueOf(TxtPass2.getPassword());
        boolean band = true;
        if ("".equals(TxtUser.getText())){
            JOptionPane.showMessageDialog( null , " Error el suario no puede ser nulo " );
            band=false;
        }
        if (a.equals(b)==false){
            JOptionPane.showMessageDialog( null , " Error las contraseñas no coinciden " );
            band =false;
        }
        if (Rad1.isSelected() != true && Rad2.isSelected() != true){
            JOptionPane.showMessageDialog( null , " Error seleccione un tipo de usuario " );
            band=false;
        }
        if(Rad1.isSelected()&& band){
            try {

                validar_usuario1();

            } catch (SQLException ex) {

                Logger.getLogger(registro.class.getName()).log(Level.SEVERE, null, ex);

            }
        }
        if(Rad2.isSelected()&& band){
            try {

                validar_usuario2();

            } catch (SQLException ex) {
                Logger.getLogger(registro.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_BtonConfActionPerformed

    public void validar_usuario1() throws SQLException{
        Connection con = getConection(); //Abriendo la conexion
        
        try {
            /// Registro Admin
            
            String user = String.valueOf(TxtUser.getText());
            String pass =  String.valueOf(TxtPass1.getPassword());
            
            ps = con.prepareStatement("insert into login (nombre_usuario,fk_tipo_usuario,contrasenia) values (?,?,?);");
            System.out.println("Aquí si llega 1 " + ps);        
            ps.setString(1, user);
            ps.setInt(2, 1);
            ps.setString(3, pass);
            ps.execute();
            System.out.println("Aquí si llega 2 "+ps.toString());
            JOptionPane.showMessageDialog(null,"Usuario registrado correctamente");
            con.close(); //Cerrando conexion
        } catch (SQLException ex) {
            Logger.getLogger(registro.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Error en registro");
            TxtUser.setText("");
            TxtPass1.setText("");
        }
    }
    
    
    public void validar_usuario2() throws SQLException{
            Connection con = getConection(); //Abriendo la conexion
        
        try {
            /// Registro Admin
            
            String user = String.valueOf(TxtUser.getText());
            String pass =  String.valueOf(TxtPass1.getPassword());
            //ps = con.prepareStatement("select * from login where nombre_usuario='Ivan' and contrasenia='nobodyloveme';");
            ps = con.prepareStatement("insert into login (nombre_usuario,fk_tipo_usuario,contrasenia) values (?,?,?);");
            System.out.println("Aquí si llega 1 " + ps);        
            ps.setString(1, user);
            ps.setInt(2, 2);
            ps.setString(3, pass);
            ps.execute();
            System.out.println("Aquí si llega 2 "+ps.toString());
            JOptionPane.showMessageDialog(null,"Usuario registrado correctamente");
            con.close(); //Cerrando conexion
        } catch (SQLException ex) {
            Logger.getLogger(registro.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Error en registro");
            TxtUser.setText("");
            TxtPass1.setText("");
        }
    }
    private void Rad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rad2ActionPerformed

    private void Rad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rad1ActionPerformed

    private void TxtPass1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtPass1MouseClicked
        // TODO add your handling code here:
        TxtPass1.setText("");
    }//GEN-LAST:event_TxtPass1MouseClicked

    private void TxtPass2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtPass2MouseClicked
        // TODO add your handling code here:
        TxtPass2.setText("");
    }//GEN-LAST:event_TxtPass2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtras;
    private javax.swing.JButton BtonConf;
    private javax.swing.JLabel Fondo;
    private javax.swing.ButtonGroup GrupoRad1;
    private javax.swing.JRadioButton Rad1;
    private javax.swing.JRadioButton Rad2;
    private javax.swing.JPasswordField TxtPass1;
    private javax.swing.JPasswordField TxtPass2;
    private javax.swing.JTextField TxtUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
